version: '3.8'

services:
  web:
    image: nfaria/nginx-ci-cd:latest
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx-ci-cd:/usr/share/nginx/html   # Mantener sincronizacion del html