name: Nginx Pipeline

on:
  push:
    branches:
      - main  # O la rama que uses

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t nfaria01/nginx-ci-cd:latest .
          docker push nfaria01/nginx-ci-cd:latest

      - name: Deploy with docker-compose
        run: |
          docker-compose pull
          docker-compose up -d --force-recreate